name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get install -y gcc make

      - name: Build the project
        run: make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: library
          path: ./lib

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: library

      - name: Run tests
        run: make test
